# coding: utf-8

"""
    WAHA - WhatsApp HTTP API

    <b>WhatsApp HTTP API</b> that you can run in a click!<br/><a href=\"/dashboard\"><b>📊 Dashboard</b></a><br/><br/>Learn more:<ul><li><a href=\"https://waha.devlike.pro/\" target=\"_blank\">Documentation</a></li><li><a href=\"https://waha.devlike.pro/docs/how-to/engines/#features\" target=\"_blank\">Supported features in engines</a></li><li><a href=\"https://github.com/devlikeapro/waha\" target=\"_blank\">GitHub - WAHA Core</a></li><li><a href=\"https://github.com/devlikeapro/waha-plus\" target=\"_blank\">GitHub - WAHA Plus</a></li></ul><p>Support the project and get WAHA Plus version!</p><ul><li><a href=\"https://waha.devlike.pro/docs/how-to/plus-version/\" target=\"_blank\">WAHA Plus</a></li><li><a href=\"https://patreon.com/wa_http_api/\" target=\"_blank\">Patreon</a></li><li><a href=\"https://boosty.to/wa-http-api/\" target=\"_blank\">Boosty</a></li><li><a href=\"https://portal.devlike.pro/\" target=\"_blank\">Patron Portal</a></li></ul>  # noqa: E501

    OpenAPI spec version: 2024.12.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Button(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'text': 'object',
        'id': 'object',
        'url': 'object',
        'phone_number': 'object',
        'copy_code': 'object',
        'type': 'object'
    }

    attribute_map = {
        'text': 'text',
        'id': 'id',
        'url': 'url',
        'phone_number': 'phoneNumber',
        'copy_code': 'copyCode',
        'type': 'type'
    }

    def __init__(self, text=None, id=None, url=None, phone_number=None, copy_code=None, type=None):  # noqa: E501
        """Button - a model defined in Swagger"""  # noqa: E501
        self._text = None
        self._id = None
        self._url = None
        self._phone_number = None
        self._copy_code = None
        self._type = None
        self.discriminator = None
        self.text = text
        if id is not None:
            self.id = id
        if url is not None:
            self.url = url
        if phone_number is not None:
            self.phone_number = phone_number
        if copy_code is not None:
            self.copy_code = copy_code
        self.type = type

    @property
    def text(self):
        """Gets the text of this Button.  # noqa: E501


        :return: The text of this Button.  # noqa: E501
        :rtype: object
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this Button.


        :param text: The text of this Button.  # noqa: E501
        :type: object
        """
        if text is None:
            raise ValueError("Invalid value for `text`, must not be `None`")  # noqa: E501

        self._text = text

    @property
    def id(self):
        """Gets the id of this Button.  # noqa: E501


        :return: The id of this Button.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Button.


        :param id: The id of this Button.  # noqa: E501
        :type: object
        """

        self._id = id

    @property
    def url(self):
        """Gets the url of this Button.  # noqa: E501


        :return: The url of this Button.  # noqa: E501
        :rtype: object
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this Button.


        :param url: The url of this Button.  # noqa: E501
        :type: object
        """

        self._url = url

    @property
    def phone_number(self):
        """Gets the phone_number of this Button.  # noqa: E501


        :return: The phone_number of this Button.  # noqa: E501
        :rtype: object
        """
        return self._phone_number

    @phone_number.setter
    def phone_number(self, phone_number):
        """Sets the phone_number of this Button.


        :param phone_number: The phone_number of this Button.  # noqa: E501
        :type: object
        """

        self._phone_number = phone_number

    @property
    def copy_code(self):
        """Gets the copy_code of this Button.  # noqa: E501


        :return: The copy_code of this Button.  # noqa: E501
        :rtype: object
        """
        return self._copy_code

    @copy_code.setter
    def copy_code(self, copy_code):
        """Sets the copy_code of this Button.


        :param copy_code: The copy_code of this Button.  # noqa: E501
        :type: object
        """

        self._copy_code = copy_code

    @property
    def type(self):
        """Gets the type of this Button.  # noqa: E501


        :return: The type of this Button.  # noqa: E501
        :rtype: object
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Button.


        :param type: The type of this Button.  # noqa: E501
        :type: object
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Button, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Button):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
