# coding: utf-8

"""
    WAHA - WhatsApp HTTP API

    <b>WhatsApp HTTP API</b> that you can run in a click!<br/><a href=\"/dashboard\"><b>📊 Dashboard</b></a><br/><br/>Learn more:<ul><li><a href=\"https://waha.devlike.pro/\" target=\"_blank\">Documentation</a></li><li><a href=\"https://waha.devlike.pro/docs/how-to/engines/#features\" target=\"_blank\">Supported features in engines</a></li><li><a href=\"https://github.com/devlikeapro/waha\" target=\"_blank\">GitHub - WAHA Core</a></li><li><a href=\"https://github.com/devlikeapro/waha-plus\" target=\"_blank\">GitHub - WAHA Plus</a></li></ul><p>Support the project and get WAHA Plus version!</p><ul><li><a href=\"https://waha.devlike.pro/docs/how-to/plus-version/\" target=\"_blank\">WAHA Plus</a></li><li><a href=\"https://patreon.com/wa_http_api/\" target=\"_blank\">Patreon</a></li><li><a href=\"https://boosty.to/wa-http-api/\" target=\"_blank\">Boosty</a></li><li><a href=\"https://portal.devlike.pro/\" target=\"_blank\">Patron Portal</a></li></ul>  # noqa: E501

    OpenAPI spec version: 2024.12.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CallData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'object',
        '_from': 'object',
        'timestamp': 'object',
        'is_video': 'object',
        'is_group': 'object'
    }

    attribute_map = {
        'id': 'id',
        '_from': 'from',
        'timestamp': 'timestamp',
        'is_video': 'isVideo',
        'is_group': 'isGroup'
    }

    def __init__(self, id=None, _from=None, timestamp=None, is_video=None, is_group=None):  # noqa: E501
        """CallData - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self.__from = None
        self._timestamp = None
        self._is_video = None
        self._is_group = None
        self.discriminator = None
        self.id = id
        if _from is not None:
            self._from = _from
        self.timestamp = timestamp
        self.is_video = is_video
        self.is_group = is_group

    @property
    def id(self):
        """Gets the id of this CallData.  # noqa: E501

        Call ID  # noqa: E501

        :return: The id of this CallData.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CallData.

        Call ID  # noqa: E501

        :param id: The id of this CallData.  # noqa: E501
        :type: object
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def _from(self):
        """Gets the _from of this CallData.  # noqa: E501


        :return: The _from of this CallData.  # noqa: E501
        :rtype: object
        """
        return self.__from

    @_from.setter
    def _from(self, _from):
        """Sets the _from of this CallData.


        :param _from: The _from of this CallData.  # noqa: E501
        :type: object
        """

        self.__from = _from

    @property
    def timestamp(self):
        """Gets the timestamp of this CallData.  # noqa: E501


        :return: The timestamp of this CallData.  # noqa: E501
        :rtype: object
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this CallData.


        :param timestamp: The timestamp of this CallData.  # noqa: E501
        :type: object
        """
        if timestamp is None:
            raise ValueError("Invalid value for `timestamp`, must not be `None`")  # noqa: E501

        self._timestamp = timestamp

    @property
    def is_video(self):
        """Gets the is_video of this CallData.  # noqa: E501


        :return: The is_video of this CallData.  # noqa: E501
        :rtype: object
        """
        return self._is_video

    @is_video.setter
    def is_video(self, is_video):
        """Sets the is_video of this CallData.


        :param is_video: The is_video of this CallData.  # noqa: E501
        :type: object
        """
        if is_video is None:
            raise ValueError("Invalid value for `is_video`, must not be `None`")  # noqa: E501

        self._is_video = is_video

    @property
    def is_group(self):
        """Gets the is_group of this CallData.  # noqa: E501


        :return: The is_group of this CallData.  # noqa: E501
        :rtype: object
        """
        return self._is_group

    @is_group.setter
    def is_group(self, is_group):
        """Sets the is_group of this CallData.


        :param is_group: The is_group of this CallData.  # noqa: E501
        :type: object
        """
        if is_group is None:
            raise ValueError("Invalid value for `is_group`, must not be `None`")  # noqa: E501

        self._is_group = is_group

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CallData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CallData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
