# coding: utf-8

"""
    WAHA - WhatsApp HTTP API

    <b>WhatsApp HTTP API</b> that you can run in a click!<br/><a href=\"/dashboard\"><b>📊 Dashboard</b></a><br/><br/>Learn more:<ul><li><a href=\"https://waha.devlike.pro/\" target=\"_blank\">Documentation</a></li><li><a href=\"https://waha.devlike.pro/docs/how-to/engines/#features\" target=\"_blank\">Supported features in engines</a></li><li><a href=\"https://github.com/devlikeapro/waha\" target=\"_blank\">GitHub - WAHA Core</a></li><li><a href=\"https://github.com/devlikeapro/waha-plus\" target=\"_blank\">GitHub - WAHA Plus</a></li></ul><p>Support the project and get WAHA Plus version!</p><ul><li><a href=\"https://waha.devlike.pro/docs/how-to/plus-version/\" target=\"_blank\">WAHA Plus</a></li><li><a href=\"https://patreon.com/wa_http_api/\" target=\"_blank\">Patreon</a></li><li><a href=\"https://boosty.to/wa-http-api/\" target=\"_blank\">Boosty</a></li><li><a href=\"https://portal.devlike.pro/\" target=\"_blank\">Patron Portal</a></li></ul>  # noqa: E501

    OpenAPI spec version: 2024.12.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Contact(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'full_name': 'object',
        'organization': 'object',
        'phone_number': 'object',
        'whatsapp_id': 'object',
        'vcard': 'object'
    }

    attribute_map = {
        'full_name': 'fullName',
        'organization': 'organization',
        'phone_number': 'phoneNumber',
        'whatsapp_id': 'whatsappId',
        'vcard': 'vcard'
    }

    def __init__(self, full_name=None, organization=None, phone_number=None, whatsapp_id=None, vcard=None):  # noqa: E501
        """Contact - a model defined in Swagger"""  # noqa: E501
        self._full_name = None
        self._organization = None
        self._phone_number = None
        self._whatsapp_id = None
        self._vcard = None
        self.discriminator = None
        self.full_name = full_name
        if organization is not None:
            self.organization = organization
        self.phone_number = phone_number
        if whatsapp_id is not None:
            self.whatsapp_id = whatsapp_id
        self.vcard = vcard

    @property
    def full_name(self):
        """Gets the full_name of this Contact.  # noqa: E501

        The full name of the contact  # noqa: E501

        :return: The full_name of this Contact.  # noqa: E501
        :rtype: object
        """
        return self._full_name

    @full_name.setter
    def full_name(self, full_name):
        """Sets the full_name of this Contact.

        The full name of the contact  # noqa: E501

        :param full_name: The full_name of this Contact.  # noqa: E501
        :type: object
        """
        if full_name is None:
            raise ValueError("Invalid value for `full_name`, must not be `None`")  # noqa: E501

        self._full_name = full_name

    @property
    def organization(self):
        """Gets the organization of this Contact.  # noqa: E501

        The organization of the contact  # noqa: E501

        :return: The organization of this Contact.  # noqa: E501
        :rtype: object
        """
        return self._organization

    @organization.setter
    def organization(self, organization):
        """Sets the organization of this Contact.

        The organization of the contact  # noqa: E501

        :param organization: The organization of this Contact.  # noqa: E501
        :type: object
        """

        self._organization = organization

    @property
    def phone_number(self):
        """Gets the phone_number of this Contact.  # noqa: E501

        The phone number of the contact  # noqa: E501

        :return: The phone_number of this Contact.  # noqa: E501
        :rtype: object
        """
        return self._phone_number

    @phone_number.setter
    def phone_number(self, phone_number):
        """Sets the phone_number of this Contact.

        The phone number of the contact  # noqa: E501

        :param phone_number: The phone_number of this Contact.  # noqa: E501
        :type: object
        """
        if phone_number is None:
            raise ValueError("Invalid value for `phone_number`, must not be `None`")  # noqa: E501

        self._phone_number = phone_number

    @property
    def whatsapp_id(self):
        """Gets the whatsapp_id of this Contact.  # noqa: E501

        The whatsapp id of the contact. DO NOT add + or @c.us  # noqa: E501

        :return: The whatsapp_id of this Contact.  # noqa: E501
        :rtype: object
        """
        return self._whatsapp_id

    @whatsapp_id.setter
    def whatsapp_id(self, whatsapp_id):
        """Sets the whatsapp_id of this Contact.

        The whatsapp id of the contact. DO NOT add + or @c.us  # noqa: E501

        :param whatsapp_id: The whatsapp_id of this Contact.  # noqa: E501
        :type: object
        """

        self._whatsapp_id = whatsapp_id

    @property
    def vcard(self):
        """Gets the vcard of this Contact.  # noqa: E501


        :return: The vcard of this Contact.  # noqa: E501
        :rtype: object
        """
        return self._vcard

    @vcard.setter
    def vcard(self, vcard):
        """Sets the vcard of this Contact.


        :param vcard: The vcard of this Contact.  # noqa: E501
        :type: object
        """
        if vcard is None:
            raise ValueError("Invalid value for `vcard`, must not be `None`")  # noqa: E501

        self._vcard = vcard

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Contact, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Contact):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
