# coding: utf-8

"""
    WAHA - WhatsApp HTTP API

    <b>WhatsApp HTTP API</b> that you can run in a click!<br/><a href=\"/dashboard\"><b>📊 Dashboard</b></a><br/><br/>Learn more:<ul><li><a href=\"https://waha.devlike.pro/\" target=\"_blank\">Documentation</a></li><li><a href=\"https://waha.devlike.pro/docs/how-to/engines/#features\" target=\"_blank\">Supported features in engines</a></li><li><a href=\"https://github.com/devlikeapro/waha\" target=\"_blank\">GitHub - WAHA Core</a></li><li><a href=\"https://github.com/devlikeapro/waha-plus\" target=\"_blank\">GitHub - WAHA Plus</a></li></ul><p>Support the project and get WAHA Plus version!</p><ul><li><a href=\"https://waha.devlike.pro/docs/how-to/plus-version/\" target=\"_blank\">WAHA Plus</a></li><li><a href=\"https://patreon.com/wa_http_api/\" target=\"_blank\">Patreon</a></li><li><a href=\"https://boosty.to/wa-http-api/\" target=\"_blank\">Boosty</a></li><li><a href=\"https://portal.devlike.pro/\" target=\"_blank\">Patron Portal</a></li></ul>  # noqa: E501

    OpenAPI spec version: 2024.12.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Label(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'object',
        'name': 'object',
        'color': 'object',
        'color_hex': 'object'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'color': 'color',
        'color_hex': 'colorHex'
    }

    def __init__(self, id=None, name=None, color=None, color_hex=None):  # noqa: E501
        """Label - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._color = None
        self._color_hex = None
        self.discriminator = None
        self.id = id
        self.name = name
        self.color = color
        self.color_hex = color_hex

    @property
    def id(self):
        """Gets the id of this Label.  # noqa: E501

        Label ID  # noqa: E501

        :return: The id of this Label.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Label.

        Label ID  # noqa: E501

        :param id: The id of this Label.  # noqa: E501
        :type: object
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this Label.  # noqa: E501

        Label name  # noqa: E501

        :return: The name of this Label.  # noqa: E501
        :rtype: object
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Label.

        Label name  # noqa: E501

        :param name: The name of this Label.  # noqa: E501
        :type: object
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def color(self):
        """Gets the color of this Label.  # noqa: E501

        Color number, not hex  # noqa: E501

        :return: The color of this Label.  # noqa: E501
        :rtype: object
        """
        return self._color

    @color.setter
    def color(self, color):
        """Sets the color of this Label.

        Color number, not hex  # noqa: E501

        :param color: The color of this Label.  # noqa: E501
        :type: object
        """
        if color is None:
            raise ValueError("Invalid value for `color`, must not be `None`")  # noqa: E501

        self._color = color

    @property
    def color_hex(self):
        """Gets the color_hex of this Label.  # noqa: E501

        Color in hex  # noqa: E501

        :return: The color_hex of this Label.  # noqa: E501
        :rtype: object
        """
        return self._color_hex

    @color_hex.setter
    def color_hex(self, color_hex):
        """Sets the color_hex of this Label.

        Color in hex  # noqa: E501

        :param color_hex: The color_hex of this Label.  # noqa: E501
        :type: object
        """
        if color_hex is None:
            raise ValueError("Invalid value for `color_hex`, must not be `None`")  # noqa: E501

        self._color_hex = color_hex

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Label, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Label):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
