# coding: utf-8

"""
    WAHA - WhatsApp HTTP API

    <b>WhatsApp HTTP API</b> that you can run in a click!<br/><a href=\"/dashboard\"><b>📊 Dashboard</b></a><br/><br/>Learn more:<ul><li><a href=\"https://waha.devlike.pro/\" target=\"_blank\">Documentation</a></li><li><a href=\"https://waha.devlike.pro/docs/how-to/engines/#features\" target=\"_blank\">Supported features in engines</a></li><li><a href=\"https://github.com/devlikeapro/waha\" target=\"_blank\">GitHub - WAHA Core</a></li><li><a href=\"https://github.com/devlikeapro/waha-plus\" target=\"_blank\">GitHub - WAHA Plus</a></li></ul><p>Support the project and get WAHA Plus version!</p><ul><li><a href=\"https://waha.devlike.pro/docs/how-to/plus-version/\" target=\"_blank\">WAHA Plus</a></li><li><a href=\"https://patreon.com/wa_http_api/\" target=\"_blank\">Patreon</a></li><li><a href=\"https://boosty.to/wa-http-api/\" target=\"_blank\">Boosty</a></li><li><a href=\"https://portal.devlike.pro/\" target=\"_blank\">Patron Portal</a></li></ul>  # noqa: E501

    OpenAPI spec version: 2024.12.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProxyConfig(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'server': 'object',
        'username': 'object',
        'password': 'object'
    }

    attribute_map = {
        'server': 'server',
        'username': 'username',
        'password': 'password'
    }

    def __init__(self, server=None, username=None, password=None):  # noqa: E501
        """ProxyConfig - a model defined in Swagger"""  # noqa: E501
        self._server = None
        self._username = None
        self._password = None
        self.discriminator = None
        self.server = server
        if username is not None:
            self.username = username
        if password is not None:
            self.password = password

    @property
    def server(self):
        """Gets the server of this ProxyConfig.  # noqa: E501


        :return: The server of this ProxyConfig.  # noqa: E501
        :rtype: object
        """
        return self._server

    @server.setter
    def server(self, server):
        """Sets the server of this ProxyConfig.


        :param server: The server of this ProxyConfig.  # noqa: E501
        :type: object
        """
        if server is None:
            raise ValueError("Invalid value for `server`, must not be `None`")  # noqa: E501

        self._server = server

    @property
    def username(self):
        """Gets the username of this ProxyConfig.  # noqa: E501


        :return: The username of this ProxyConfig.  # noqa: E501
        :rtype: object
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this ProxyConfig.


        :param username: The username of this ProxyConfig.  # noqa: E501
        :type: object
        """

        self._username = username

    @property
    def password(self):
        """Gets the password of this ProxyConfig.  # noqa: E501


        :return: The password of this ProxyConfig.  # noqa: E501
        :rtype: object
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this ProxyConfig.


        :param password: The password of this ProxyConfig.  # noqa: E501
        :type: object
        """

        self._password = password

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProxyConfig, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProxyConfig):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
