# coding: utf-8

"""
    WAHA - WhatsApp HTTP API

    <b>WhatsApp HTTP API</b> that you can run in a click!<br/><a href=\"/dashboard\"><b>📊 Dashboard</b></a><br/><br/>Learn more:<ul><li><a href=\"https://waha.devlike.pro/\" target=\"_blank\">Documentation</a></li><li><a href=\"https://waha.devlike.pro/docs/how-to/engines/#features\" target=\"_blank\">Supported features in engines</a></li><li><a href=\"https://github.com/devlikeapro/waha\" target=\"_blank\">GitHub - WAHA Core</a></li><li><a href=\"https://github.com/devlikeapro/waha-plus\" target=\"_blank\">GitHub - WAHA Plus</a></li></ul><p>Support the project and get WAHA Plus version!</p><ul><li><a href=\"https://waha.devlike.pro/docs/how-to/plus-version/\" target=\"_blank\">WAHA Plus</a></li><li><a href=\"https://patreon.com/wa_http_api/\" target=\"_blank\">Patreon</a></li><li><a href=\"https://boosty.to/wa-http-api/\" target=\"_blank\">Boosty</a></li><li><a href=\"https://portal.devlike.pro/\" target=\"_blank\">Patron Portal</a></li></ul>  # noqa: E501

    OpenAPI spec version: 2024.12.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ServerStatusResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'start_timestamp': 'object',
        'uptime': 'object',
        'worker': 'WorkerInfo'
    }

    attribute_map = {
        'start_timestamp': 'startTimestamp',
        'uptime': 'uptime',
        'worker': 'worker'
    }

    def __init__(self, start_timestamp=None, uptime=None, worker=None):  # noqa: E501
        """ServerStatusResponse - a model defined in Swagger"""  # noqa: E501
        self._start_timestamp = None
        self._uptime = None
        self._worker = None
        self.discriminator = None
        self.start_timestamp = start_timestamp
        self.uptime = uptime
        self.worker = worker

    @property
    def start_timestamp(self):
        """Gets the start_timestamp of this ServerStatusResponse.  # noqa: E501

        The timestamp when the server started (milliseconds).  # noqa: E501

        :return: The start_timestamp of this ServerStatusResponse.  # noqa: E501
        :rtype: object
        """
        return self._start_timestamp

    @start_timestamp.setter
    def start_timestamp(self, start_timestamp):
        """Sets the start_timestamp of this ServerStatusResponse.

        The timestamp when the server started (milliseconds).  # noqa: E501

        :param start_timestamp: The start_timestamp of this ServerStatusResponse.  # noqa: E501
        :type: object
        """
        if start_timestamp is None:
            raise ValueError("Invalid value for `start_timestamp`, must not be `None`")  # noqa: E501

        self._start_timestamp = start_timestamp

    @property
    def uptime(self):
        """Gets the uptime of this ServerStatusResponse.  # noqa: E501

        The uptime of the server in milliseconds.  # noqa: E501

        :return: The uptime of this ServerStatusResponse.  # noqa: E501
        :rtype: object
        """
        return self._uptime

    @uptime.setter
    def uptime(self, uptime):
        """Sets the uptime of this ServerStatusResponse.

        The uptime of the server in milliseconds.  # noqa: E501

        :param uptime: The uptime of this ServerStatusResponse.  # noqa: E501
        :type: object
        """
        if uptime is None:
            raise ValueError("Invalid value for `uptime`, must not be `None`")  # noqa: E501

        self._uptime = uptime

    @property
    def worker(self):
        """Gets the worker of this ServerStatusResponse.  # noqa: E501


        :return: The worker of this ServerStatusResponse.  # noqa: E501
        :rtype: WorkerInfo
        """
        return self._worker

    @worker.setter
    def worker(self, worker):
        """Sets the worker of this ServerStatusResponse.


        :param worker: The worker of this ServerStatusResponse.  # noqa: E501
        :type: WorkerInfo
        """
        if worker is None:
            raise ValueError("Invalid value for `worker`, must not be `None`")  # noqa: E501

        self._worker = worker

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ServerStatusResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ServerStatusResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
