# coding: utf-8

"""
    WAHA - WhatsApp HTTP API

    <b>WhatsApp HTTP API</b> that you can run in a click!<br/><a href=\"/dashboard\"><b>📊 Dashboard</b></a><br/><br/>Learn more:<ul><li><a href=\"https://waha.devlike.pro/\" target=\"_blank\">Documentation</a></li><li><a href=\"https://waha.devlike.pro/docs/how-to/engines/#features\" target=\"_blank\">Supported features in engines</a></li><li><a href=\"https://github.com/devlikeapro/waha\" target=\"_blank\">GitHub - WAHA Core</a></li><li><a href=\"https://github.com/devlikeapro/waha-plus\" target=\"_blank\">GitHub - WAHA Plus</a></li></ul><p>Support the project and get WAHA Plus version!</p><ul><li><a href=\"https://waha.devlike.pro/docs/how-to/plus-version/\" target=\"_blank\">WAHA Plus</a></li><li><a href=\"https://patreon.com/wa_http_api/\" target=\"_blank\">Patreon</a></li><li><a href=\"https://boosty.to/wa-http-api/\" target=\"_blank\">Boosty</a></li><li><a href=\"https://portal.devlike.pro/\" target=\"_blank\">Patron Portal</a></li></ul>  # noqa: E501

    OpenAPI spec version: 2024.12.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class VideoRemoteFile(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'mimetype': 'object',
        'filename': 'object',
        'url': 'object'
    }

    attribute_map = {
        'mimetype': 'mimetype',
        'filename': 'filename',
        'url': 'url'
    }

    def __init__(self, mimetype=None, filename=None, url=None):  # noqa: E501
        """VideoRemoteFile - a model defined in Swagger"""  # noqa: E501
        self._mimetype = None
        self._filename = None
        self._url = None
        self.discriminator = None
        self.mimetype = mimetype
        self.filename = filename
        self.url = url

    @property
    def mimetype(self):
        """Gets the mimetype of this VideoRemoteFile.  # noqa: E501

        MIME type of the attachment.  # noqa: E501

        :return: The mimetype of this VideoRemoteFile.  # noqa: E501
        :rtype: object
        """
        return self._mimetype

    @mimetype.setter
    def mimetype(self, mimetype):
        """Sets the mimetype of this VideoRemoteFile.

        MIME type of the attachment.  # noqa: E501

        :param mimetype: The mimetype of this VideoRemoteFile.  # noqa: E501
        :type: object
        """
        if mimetype is None:
            raise ValueError("Invalid value for `mimetype`, must not be `None`")  # noqa: E501

        self._mimetype = mimetype

    @property
    def filename(self):
        """Gets the filename of this VideoRemoteFile.  # noqa: E501

        Document file name. Optional  # noqa: E501

        :return: The filename of this VideoRemoteFile.  # noqa: E501
        :rtype: object
        """
        return self._filename

    @filename.setter
    def filename(self, filename):
        """Sets the filename of this VideoRemoteFile.

        Document file name. Optional  # noqa: E501

        :param filename: The filename of this VideoRemoteFile.  # noqa: E501
        :type: object
        """
        if filename is None:
            raise ValueError("Invalid value for `filename`, must not be `None`")  # noqa: E501

        self._filename = filename

    @property
    def url(self):
        """Gets the url of this VideoRemoteFile.  # noqa: E501


        :return: The url of this VideoRemoteFile.  # noqa: E501
        :rtype: object
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this VideoRemoteFile.


        :param url: The url of this VideoRemoteFile.  # noqa: E501
        :type: object
        """
        if url is None:
            raise ValueError("Invalid value for `url`, must not be `None`")  # noqa: E501

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VideoRemoteFile, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VideoRemoteFile):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
