# coding: utf-8

"""
    WAHA - WhatsApp HTTP API

    <b>WhatsApp HTTP API</b> that you can run in a click!<br/><a href=\"/dashboard\"><b>📊 Dashboard</b></a><br/><br/>Learn more:<ul><li><a href=\"https://waha.devlike.pro/\" target=\"_blank\">Documentation</a></li><li><a href=\"https://waha.devlike.pro/docs/how-to/engines/#features\" target=\"_blank\">Supported features in engines</a></li><li><a href=\"https://github.com/devlikeapro/waha\" target=\"_blank\">GitHub - WAHA Core</a></li><li><a href=\"https://github.com/devlikeapro/waha-plus\" target=\"_blank\">GitHub - WAHA Plus</a></li></ul><p>Support the project and get WAHA Plus version!</p><ul><li><a href=\"https://waha.devlike.pro/docs/how-to/plus-version/\" target=\"_blank\">WAHA Plus</a></li><li><a href=\"https://patreon.com/wa_http_api/\" target=\"_blank\">Patreon</a></li><li><a href=\"https://boosty.to/wa-http-api/\" target=\"_blank\">Boosty</a></li><li><a href=\"https://portal.devlike.pro/\" target=\"_blank\">Patron Portal</a></li></ul>  # noqa: E501

    OpenAPI spec version: 2024.12.4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WAHAPresenceData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'participant': 'object',
        'last_seen': 'object',
        'last_known_presence': 'object'
    }

    attribute_map = {
        'participant': 'participant',
        'last_seen': 'lastSeen',
        'last_known_presence': 'lastKnownPresence'
    }

    def __init__(self, participant=None, last_seen=None, last_known_presence=None):  # noqa: E501
        """WAHAPresenceData - a model defined in Swagger"""  # noqa: E501
        self._participant = None
        self._last_seen = None
        self._last_known_presence = None
        self.discriminator = None
        self.participant = participant
        if last_seen is not None:
            self.last_seen = last_seen
        self.last_known_presence = last_known_presence

    @property
    def participant(self):
        """Gets the participant of this WAHAPresenceData.  # noqa: E501

        Chat ID - participant or contact id  # noqa: E501

        :return: The participant of this WAHAPresenceData.  # noqa: E501
        :rtype: object
        """
        return self._participant

    @participant.setter
    def participant(self, participant):
        """Sets the participant of this WAHAPresenceData.

        Chat ID - participant or contact id  # noqa: E501

        :param participant: The participant of this WAHAPresenceData.  # noqa: E501
        :type: object
        """
        if participant is None:
            raise ValueError("Invalid value for `participant`, must not be `None`")  # noqa: E501

        self._participant = participant

    @property
    def last_seen(self):
        """Gets the last_seen of this WAHAPresenceData.  # noqa: E501


        :return: The last_seen of this WAHAPresenceData.  # noqa: E501
        :rtype: object
        """
        return self._last_seen

    @last_seen.setter
    def last_seen(self, last_seen):
        """Sets the last_seen of this WAHAPresenceData.


        :param last_seen: The last_seen of this WAHAPresenceData.  # noqa: E501
        :type: object
        """

        self._last_seen = last_seen

    @property
    def last_known_presence(self):
        """Gets the last_known_presence of this WAHAPresenceData.  # noqa: E501


        :return: The last_known_presence of this WAHAPresenceData.  # noqa: E501
        :rtype: object
        """
        return self._last_known_presence

    @last_known_presence.setter
    def last_known_presence(self, last_known_presence):
        """Sets the last_known_presence of this WAHAPresenceData.


        :param last_known_presence: The last_known_presence of this WAHAPresenceData.  # noqa: E501
        :type: object
        """
        if last_known_presence is None:
            raise ValueError("Invalid value for `last_known_presence`, must not be `None`")  # noqa: E501

        self._last_known_presence = last_known_presence

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WAHAPresenceData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WAHAPresenceData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
